### ISSUE TITLE
加友链吗

### ISSUE THREAD

**Issue by elykia-cn** [SteveZMTstudios/articles#24]
- name: Elykia
  link: https://blog.elykia.cn/
  avatar: https://bu.dusays.com/2024/10/25/671b2438203a6.gif
  descr: 致以无暇之人
  siteshot: https://bu.dusays.com/2024/10/25/671b50dc2dd2b.png

**Comment by SteveZMTstudios** [comment]
互加吧，一会合并发布 ﾚ(ﾟ∀ﾟ;)ﾍ=З=З=З

**Comment by elykia-cn** [comment]
https://blog.elykia.cn/link/
已加

**Comment by SteveZMTstudios** [comment]
好的，等我一会
我加点东西就推

**Comment by SteveZMTstudios** [comment]
735fa2dd6e55ee0d17366f069bce3333b200bbf6
